git:
  pagers:
    - externalDiffCommand: difft --color=always --display=side-by-side
gui:
  nerdFontsVersion: "3"

customCommands:
  - key: "<C-c>"
    context: "files"
    description: "Gitmojiä»˜ãã§ã‚³ãƒŸãƒƒãƒˆ (Custom command)"
    prompts:
      - type: "menu"
        title: "What kind of commit?"
        key: "Emoji"
        options:
          # ref: files/config/git/commit_template.txt
          - name: ":sparkles:"
            description: "âœ¨ Introduce new features"
            value: ":sparkles:"
          - name: ":zap:"
            description: "âš¡ Improve performance"
            value: ":zap:"
          - name: ":fire:"
            description: "ğŸ”¥ Remove code or files"
            value: ":fire:"
          - name: ":bug:"
            description: "ğŸ› Fix bugs"
            value: ":bug:"
          - name: "adhesive_bandage:"
            description: "ğŸ©¹ Simple fix for a non-critical issue"
            value: ":adhesive_bandage:"
          - name: ":ambulance:"
            description: "ğŸš‘ Critical hotfix"
            value: ":ambulance:"
          - name: ":recycle:"
            description: "â™»ï¸ Refactor code"
            value: ":recycle:"
          - name: ":art:"
            description: "ğŸ¨ Improve structure/format of the code"
            value: ":art:"
          - name: ":arrow_up:"
            description: "â¬†ï¸ Upgrade dependencies"
            value: ":arrow_up:"
          - name: ":memo:"
            description: "ğŸ“ Add or update documentation"
            value: ":memo:"
          - name: ":white_check_mark:"
            description: "âœ… Add, update, or pass tests"
            value: ":white_check_mark:"
          - name: ":tada:"
            description: "ğŸ‰ Begin a project"
            value: ":tada:"
          - name: ":twisted_rightwards_arrows:"
            description: "ğŸ”€ Merge branches"
            value: ":twisted_rightwards_arrows:"
          - name: ":construction:"
            description: "ğŸš§ Work in progress"
            value: ":construction:"
          - name: ":rocket:"
            description: "ğŸš€ Deploy stuff"
            value: ":rocket:"
          - name: ":bookmark:"
            description: "ğŸ”– Release / Version tags"
            value: ":bookmark:"
      - type: "input"
        title: "Enter the Message"
        key: "Message"
        initialValue: ""
      - type: "confirm"
        title: "Commit"
        body: "Commit with the message '{{.Form.Emoji}} {{.Form.Message}}'. Is this okay?"
    command: 'git commit -m "{{.Form.Emoji}} {{.Form.Message}}"'
    loadingText: "Commiting..."
