git:
  pagers:
    - externalDiffCommand: difft --color=always --display=side-by-side
    - pager: delta --dark --paging=never
gui:
  nerdFontsVersion: "3"

customCommands:
  - key: C
    context: global
    command: git commit -v
    description: Commit changes with git editor
    output: terminal
