# ref:
# starship configuration reference: https://starship.rs/config/
# inspired by pure theme: https://github.com/sindresorhus/pure
# nerd font cheat sheet: https://www.nerdfonts.com/cheat-sheet
# One Dark Color Palette: https://www.figma.com/community/file/1137445418485757476

# piece of One Dark color palette:
#     fg: #56B6C2 / #61AFEF / #C678DD / #98C379 / #E06C75 / #BE5046
#     bg: #282C34

format = """
$username[@](fg:#AAB2BF)$hostname$localip$directory\
$git_branch$git_commit$git_state$git_status\
$nix_shell\
\n\
$character
"""
add_newline = false

[username]
format = "[$user]($style)"
style_user = "fg:#66CDAA"
style_root = "fg:#E9967A"
show_always = true

[hostname]
format = "[$hostname]($style)"
style = "fg:#66CDAA"
ssh_only = false

[localip]
format = "([$localipv4]($style))"
style = "fig:#66CDAA"
ssh_only = true
disabled = false

[directory]
format = "[$read_only]($read_only_style) [$path]($style) "
style = "fg:#FFB6C1"
read_only = "\uf023 "                                      #  (nf-fa-lock)
read_only_style = "fg:#ABB2BF"
truncate_to_repo = true
truncation_length = 0

[character]
format = "$symbol "
success_symbol = "[\uf00c \uf054](green)" #     (nf-fa-check nf-fa-chevron_right)
error_symbol = "[\uf00d \uf054](red)"     #   (nf-fa-remove nf-fa-chevron_right)

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "fg:#98C379"
symbol = "\ue725 "                                    #  (nf-dev-git_branch)
always_show_remote = false
truncation_length = 9223372036854775807
truncation_symbol = "…"
only_attached = false
ignore_branches = []

[git_commit]
format = '[\($tag$hash\)]($style) '
style = "fg:#98C379"
only_detached = true
tag_disabled = true
tag_max_candidates = 0
tag_symbol = "\uf412 "              #  (nf-oct-tag)
commit_hash_length = 7

[git_state]
format = '[\($state( $progress_current/$progress_total)\) ]($style)'
style = "fg:#98C379"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"

[git_status]
format = '[$ahead_behind  $all_status]($style)'
style = "fg:#98C379"
conflicted = "= "
ahead = "\u21e1 "                               # ⇡
behind = "\u21e3 "                              # ⇣
diverged = "\ue728 "                            #  (nf-dev-git_compare)
up_to_date = "\uf05d "                          #  (nf-fa-circle_check)
untracked = "\uf128 "                           #  (nf-fa-question)
stashed = "\uf0d8 "                             #  (nf-fa-caret_up)
modified = "\uf044 "                            #  (nf-fa-edit)
renamed = "\uf45a "                             #  (nf-oct-diff_renamed)
deleted = "\u2718 "                             # ✘
staged = "\uf067 "                              #  (nf-fa-plus)
ignore_submodules = false

[nix_shell]
heuristic = true
