[helpers]

[default]
depends = [
    "clang-format",
    "ghostty",
    "git",
    "lazygit",
    "mise",
    "neovide",
    "neovim",
    "wezterm",
    "zellij",
    "zsh",
]

[clang-format.files]
"files/clang-format" = "~/.clang-format"

[ghostty.files]
"files/config/ghostty/config" = "~/.config/ghostty/config"

[git.files]
"files/gitconfig" = "~/.gitconfig"
"files/config/git/commit_template.gitconfig" = "~/.config/git/commit_template.gitconfig"
"files/config/git/commit_template.txt" = "~/.config/git/commit_template.txt"
"files/config/git/diff.gitconfig" = "~/.config/git/diff.gitconfig"

[lazygit.files]
"files/config/lazygit/config.yml" = "~/.config/lazygit/config.yml"

[mise.files]
"files/config/mise/config.toml" = "~/.config/mise/config.toml"

[neovide.files]
"files/config/neovide/config.toml" = "~/.config/neovide/config.toml"

[neovim.files]
"files/config/nvim/init.lua" = "~/.config/nvim/init.lua"

"files/config/nvim/lua/base.lua" = "~/.config/nvim/lua/base.lua"
"files/config/nvim/lua/keymaps.lua" = "~/.config/nvim/lua/keymaps.lua"
"files/config/nvim/lua/lazy-nvim.lua" = "~/.config/nvim/lua/lazy-nvim.lua"
"files/config/nvim/lua/lsp.lua" = "~/.config/nvim/lua/lsp.lua"
"files/config/nvim/lua/neovide.lua" = "~/.config/nvim/lua/neovide.lua"

"files/config/nvim/lua/plugins/blink-cmp.lua" = "~/.config/nvim/lua/plugins/blink-cmp.lua"
"files/config/nvim/lua/plugins/ergoterm.lua" = "~/.config/nvim/lua/plugins/ergoterm.lua"
"files/config/nvim/lua/plugins/gitsigns.lua" = "~/.config/nvim/lua/plugins/gitsigns.lua"
"files/config/nvim/lua/plugins/mason-lspconfig.lua" = "~/.config/nvim/lua/plugins/lsp/init.lua"
"files/config/nvim/lua/plugins/oil.lua" = "~/.config/nvim/lua/plugins/oil.lua"
"files/config/nvim/lua/plugins/remote-nvim.lua" = "~/.config/nvim/lua/plugins/remote-nvim.lua"
"files/config/nvim/lua/plugins/sidekick.lua" = "~/.config/nvim/lua/plugins/sidekick.lua"
"files/config/nvim/lua/plugins/telescope-frecency.lua" = "~/.config/nvim/lua/plugins/telescope-frecency.lua"
"files/config/nvim/lua/plugins/telescope.lua" = "~/.config/nvim/lua/plugins/telescope.lua"
"files/config/nvim/lua/plugins/treesitter.lua" = "~/.config/nvim/lua/plugins/treesitter.lua"
"files/config/nvim/lua/plugins/treesitter-context.lua" = "~/.config/nvim/lua/plugins/treesitter-context.lua"
"files/config/nvim/lua/plugins/treesitter-textobjects.lua" = "~/.config/nvim/lua/plugins/treesitter-textobjects.lua"

"files/config/nvim/lua/plugins/ui/colorscheme.lua" = "~/.config/nvim/lua/plugins/ui/colorschme.lua"
"files/config/nvim/lua/plugins/ui/fidget.lua" = "~/.config/nvim/lua/plugins/ui/fidget.lua"
"files/config/nvim/lua/plugins/ui/lualine.lua" = "~/.config/nvim/lua/plugins/ui/lualine.lua"
"files/config/nvim/lua/plugins/ui/mini-icons.lua" = "~/.config/nvim/lua/plugins/ui/mini-icons.lua"
"files/config/nvim/lua/plugins/ui/scrollbar.lua" = "~/.config/nvim/lua/plugins/ui/scrollbar.lua"
"files/config/nvim/lua/plugins/ui/smear-cursor.lua" = "~/.config/nvim/lua/plugins/ui/smear-cursor.lua"
"files/config/nvim/lua/plugins/ui/themes/kanagawa.lua" = "~/.config/nvim/lua/plugins/ui/themes/kanagawa.lua"

"files/config/nvim/lua/plugins/util/autopairs.lua" = "~/.config/nvim/lua/plugins/util/autopairs.lua"
"files/config/nvim/lua/plugins/util/colorizer.lua" = "~/.config/nvim/lua/plugins/util/colorizer.lua"
"files/config/nvim/lua/plugins/util/conform.lua" = "~/.config/nvim/lua/plugins/util/conform.lua"
"files/config/nvim/lua/plugins/util/dashboard.lua" = "~/.config/nvim/lua/plugins/util/dashboard.lua"
"files/config/nvim/lua/plugins/util/flash.lua" = "~/.config/nvim/lua/plugins/util/flash.lua"
"files/config/nvim/lua/plugins/util/hlslens.lua" = "~/.config/nvim/lua/plugins/util/hlslens.lua"
"files/config/nvim/lua/plugins/util/inc-rename.lua" = "~/.config/nvim/lua/plugins/util/inc-rename.lua"
"files/config/nvim/lua/plugins/util/markview.lua" = "~/.config/nvim/lua/plugins/util/markview.lua"
"files/config/nvim/lua/plugins/util/origami.lua" = "~/.config/nvim/lua/plugins/util/origami.lua"
"files/config/nvim/lua/plugins/util/smart-splits.lua" = "~/.config/nvim/lua/plugins/util/smart-splits.lua"
"files/config/nvim/lua/plugins/util/startuptime.lua" = "~/.config/nvim/lua/plugins/util/startuptime.lua"
"files/config/nvim/lua/plugins/util/which-key.lua" = "~/.config/nvim/lua/plugins/util/which-key.lua"

"files/config/nvim/after/lsp/copilot.lua" = "~/.config/nvim/after/lsp/copilot.lua"
"files/config/nvim/after/lsp/lua_ls.lua" = "~/.config/nvim/after/lsp/lua_ls.lua"

[wezterm.files]
"files/config/wezterm/wezterm.lua" = "~/.config/wezterm/wezterm.lua"
"files/config/wezterm/font.lua" = "~/.config/wezterm/font.lua"
"files/config/wezterm/keymaps.lua" = "~/.config/wezterm/keymaps.lua"
"files/config/wezterm/plugins/smart-splits-nvim.lua" = "~/.config/wezterm/plugins/smart-splits-nvim.lua"
"files/config/wezterm/themes/common.lua" = "~/.config/wezterm/themes/common.lua"
"files/config/wezterm/themes/no-image.lua" = "~/.config/wezterm/themes/no-image.lua"
"files/config/wezterm/themes/use-image.lua" = "~/.config/wezterm/themes/use-image.lua"

[zellij.files]
"files/config/zellij/config.kdl" = "~/.config/zellij/config.kdl"

[zsh.files]
"files/zshrc" = "~/.zshrc"
"files/config/starship.toml" = "~/.config/starship.toml"
"files/config/sheldon/plugins.toml" = "~/.config/sheldon/plugins.toml"
"files/config/zsh/alias.zsh" = "~/.config/zsh/alias.zsh"
"files/config/zsh/completion.zsh" = "~/.config/zsh/completion.zsh"
"files/config/zsh/hook.zsh" = "~/.config/zsh/hook.zsh"
"files/config/zsh/option.zsh" = "~/.config/zsh/option.zsh"
"files/config/zsh/ssh-agent.zsh" = "~/.config/zsh/ssh-agent.zsh"
"files/config/zsh/style.zsh" = "~/.config/zsh/style.zsh"

[settings]
default_target_type = "symbolic"
