[helpers]

[default]
depends = ["clang-format", "ghostty", "git", "lazygit", "mise", "neovim", "wezterm", "zellij", "zsh"]

[clang-format.files]
"files/clang-format" = "~/.clang-format"

[ghostty.files]
"files/config/ghostty/config" = "~/.config/ghostty/config"

[git.files]
"files/gitconfig"                            = "~/.gitconfig"
"files/config/git/commit_template.gitconfig" = "~/.config/git/commit_template.gitconfig"
"files/config/git/commit_template.txt"       = "~/.config/git/commit_template.txt"
"files/config/git/diff.gitconfig"            = "~/.config/git/diff.gitconfig"

[lazygit.files]
"files/config/lazygit/config.yml"            = "~/.config/lazygit/config.yml"

[mise.files]
"files/config/mise/config.toml" = "~/.config/mise/config.toml"

[neovim.files]
"files/config/nvim/init.lua"                         = "~/.config/nvim/init.lua"

"files/config/nvim/lua/base.lua"                     = "~/.config/nvim/lua/base.lua"
"files/config/nvim/lua/keymaps.lua"                  = "~/.config/nvim/lua/keymaps.lua"
"files/config/nvim/lua/lazy-nvim.lua"                = "~/.config/nvim/lua/lazy-nvim.lua"

"files/config/nvim/lua/plugins/blink-cmp.lua"        = "~/.config/nvim/lua/plugins/blink-cmp.lua"
"files/config/nvim/lua/plugins/copilot.lua"          = "~/.config/nvim/lua/plugins/copilot.lua"
"files/config/nvim/lua/plugins/lazygit.lua"          = "~/.config/nvim/lua/plugins/lazygit.lua"
"files/config/nvim/lua/plugins/neo-tree.lua"         = "~/.config/nvim/lua/plugins/neo-tree.lua"
"files/config/nvim/lua/plugins/remote-nvim.lua"      = "~/.config/nvim/lua/plugins/remote-nvim.lua"
"files/config/nvim/lua/plugins/telescope.lua"        = "~/.config/nvim/lua/plugins/telescope.lua"
"files/config/nvim/lua/plugins/toggleterm.lua"       = "~/.config/nvim/lua/plugins/toggleterm.lua"
"files/config/nvim/lua/plugins/treesitter.lua"       = "~/.config/nvim/lua/plugins/treesitter.lua"
"files/config/nvim/lua/plugins/yazi.lua"             = "~/.config/nvim/lua/plugins/yazi.lua"

"files/config/nvim/lua/plugins/lsp/init.lua"         = "~/.config/nvim/lua/plugins/lsp/init.lua"
"files/config/nvim/lua/plugins/lsp/lua_ls.lua"       = "~/.config/nvim/lua/plugins/lsp/lua_ls.lua"

"files/config/nvim/lua/plugins/ui/alpha.lua"         = "~/.config/nvim/lua/plugins/ui/alpha.lua"
"files/config/nvim/lua/plugins/ui/bufresize.lua"     = "~/.config/nvim/lua/plugins/ui/bufresize.lua"
"files/config/nvim/lua/plugins/ui/kanagawa.lua"      = "~/.config/nvim/lua/plugins/ui/kanagawa.lua"
"files/config/nvim/lua/plugins/ui/lsp-colors.lua"    = "~/.config/nvim/lua/plugins/ui/lsp-colors.lua"
"files/config/nvim/lua/plugins/ui/lualine.lua"       = "~/.config/nvim/lua/plugins/ui/lualine.lua"
"files/config/nvim/lua/plugins/ui/modes.lua"         = "~/.config/nvim/lua/plugins/ui/modes.lua"
"files/config/nvim/lua/plugins/ui/neoscroll.lua"     = "~/.config/nvim/lua/plugins/ui/neoscroll.lua"
"files/config/nvim/lua/plugins/ui/noice.lua"         = "~/.config/nvim/lua/plugins/ui/noice.lua"
"files/config/nvim/lua/plugins/ui/notify.lua"        = "~/.config/nvim/lua/plugins/ui/notify.lua"
"files/config/nvim/lua/plugins/ui/scrollbar.lua"     = "~/.config/nvim/lua/plugins/ui/scrollbar.lua" 
"files/config/nvim/lua/plugins/ui/smear-cursor.lua"  = "~/.config/nvim/lua/plugins/ui/smear-cursor.lua"

"files/config/nvim/lua/plugins/util/autopairs.lua"   = "~/.config/nvim/lua/plugins/util/autopairs.lua"
"files/config/nvim/lua/plugins/util/bufferline.lua"  = "~/.config/nvim/lua/plugins/util/bufferline.lua"
"files/config/nvim/lua/plugins/util/comment.lua"     = "~/.config/nvim/lua/plugins/util/comment.lua"
"files/config/nvim/lua/plugins/util/hop.lua"         = "~/.config/nvim/lua/plugins/util/hop.lua"
"files/config/nvim/lua/plugins/util/markview.lua"    = "~/.config/nvim/lua/plugins/util/markview.lua"
"files/config/nvim/lua/plugins/util/startuptime.lua" = "~/.config/nvim/lua/plugins/util/startuptime.lua"
"files/config/nvim/lua/plugins/util/which_key.lua"   = "~/.config/nvim/lua/plugins/util/which_key.lua"

[wezterm.files]
"files/config/wezterm/wezterm.lua"          = "~/.config/wezterm/wezterm.lua"
"files/config/wezterm/font.lua"             = "~/.config/wezterm/font.lua"
"files/config/wezterm/keybindings/init.lua" = "~/.config/wezterm/keybindings/init.lua"
"files/config/wezterm/keybindings/keys.lua" = "~/.config/wezterm/keybindings/keys.lua"
"files/config/wezterm/themes/init.lua"      = "~/.config/wezterm/themes/init.lua"
"files/config/wezterm/themes/no_image.lua"  = "~/.config/wezterm/themes/no_image.lua"
"files/config/wezterm/themes/use_image.lua" = "~/.config/wezterm/themes/use_image.lua"

[zellij.files]
"files/config/zellij/config.kdl"     = "~/.config/zellij/config.kdl"
"files/config/zellij/completion.zsh" = "~/.config/zellij/completion.zsh"

[zsh.files]
"files/zshrc"                       = "~/.zshrc"
"files/config/starship.toml"        = "~/.config/starship.toml"
"files/config/sheldon/plugins.toml" = "~/.config/sheldon/plugins.toml"
"files/config/zsh/alias.zsh"        = "~/.config/zsh/alias.zsh"
"files/config/zsh/completion.zsh"   = "~/.config/zsh/completion.zsh"
"files/config/zsh/hook.zsh"         = "~/.config/zsh/hook.zsh"
"files/config/zsh/option.zsh"       = "~/.config/zsh/option.zsh"
"files/config/zsh/ssh-agent.zsh"    = "~/.config/zsh/ssh-agent.zsh"
"files/config/zsh/style.zsh"        = "~/.config/zsh/style.zsh"

[settings]
default_target_type = "symbolic"
