[helpers]

[default]
depends = ["clang-format", "ghostty", "git", "lazygit", "mise", "neovim", "wezterm", "zellij", "zsh"]

[clang-format.files]
"files/clang-format" = "~/.clang-format"

[ghostty.files]
"files/config/ghostty/config" = "~/.config/ghostty/config"

[git.files]
"files/gitconfig"                            = "~/.gitconfig"
"files/config/git/commit_template.gitconfig" = "~/.config/git/commit_template.gitconfig"
"files/config/git/commit_template.txt"       = "~/.config/git/commit_template.txt"
"files/config/git/diff.gitconfig"            = "~/.config/git/diff.gitconfig"

[lazygit.files]
"files/config/lazygit/config.yml"            = "~/.config/lazygit/config.yml"

[mise.files]
"files/config/mise/config.toml" = "~/.config/mise/config.toml"

[neovim.files]
"files/config/nvim/init.lua"                        = "~/.config/nvim/init.lua"
"files/config/nvim/lua/base.lua"                    = "~/.config/nvim/lua/base.lua"
"files/config/nvim/lua/keymaps.lua"                 = "~/.config/nvim/lua/keymaps.lua"
"files/config/nvim/lua/lazy_nvim.lua"               = "~/.config/nvim/lua/lazy_nvim.lua"
"files/config/nvim/lua/plugins/alpha.lua"           = "~/.config/nvim/lua/plugins/alpha.lua"
"files/config/nvim/lua/plugins/autopairs.lua"       = "~/.config/nvim/lua/plugins/autopairs.lua"
"files/config/nvim/lua/plugins/bufferline.lua"      = "~/.config/nvim/lua/plugins/bufferline.lua"
"files/config/nvim/lua/plugins/bufresize.lua"       = "~/.config/nvim/lua/plugins/bufresize.lua"
"files/config/nvim/lua/plugins/comment.lua"         = "~/.config/nvim/lua/plugins/comment.lua"
"files/config/nvim/lua/plugins/copilot.lua"         = "~/.config/nvim/lua/plugins/copilot.lua"
"files/config/nvim/lua/plugins/fm.lua"              = "~/.config/nvim/lua/plugins/fm.lua"
"files/config/nvim/lua/plugins/kanagawa.lua"        = "~/.config/nvim/lua/plugins/kanagawa.lua"
"files/config/nvim/lua/plugins/lsp-colors.lua"      = "~/.config/nvim/lua/plugins/lsp-colors.lua"
"files/config/nvim/lua/plugins/lualine.lua"         = "~/.config/nvim/lua/plugins/lualine.lua"
"files/config/nvim/lua/plugins/mason-lspconfig.lua" = "~/.config/nvim/lua/plugins/mason-lspconfig.lua"
"files/config/nvim/lua/plugins/modes.lua"           = "~/.config/nvim/lua/plugins/modes.lua"
"files/config/nvim/lua/plugins/neo-tree.lua"        = "~/.config/nvim/lua/plugins/neo-tree.lua"
"files/config/nvim/lua/plugins/noice.lua"           = "~/.config/nvim/lua/plugins/noice.lua"
"files/config/nvim/lua/plugins/notify.lua"          = "~/.config/nvim/lua/plugins/notify.lua"
"files/config/nvim/lua/plugins/remote-nvim.lua"     = "~/.config/nvim/lua/plugins/remote-nvim.lua"
"files/config/nvim/lua/plugins/scrollbar.lua"       = "~/.config/nvim/lua/plugins/scrollbar.lua"
"files/config/nvim/lua/plugins/telescope.lua"       = "~/.config/nvim/lua/plugins/telescope.lua"
"files/config/nvim/lua/plugins/toggleterm.lua"      = "~/.config/nvim/lua/plugins/toggleterm.lua"
"files/config/nvim/lua/plugins/vim-startuptime.lua" = "~/.config/nvim/lua/plugins/vim-startuptime.lua"
"files/config/nvim/lua/plugins/which_key.lua"       = "~/.config/nvim/lua/plugins/which_key.lua"

[wezterm.files]
"files/config/wezterm/wezterm.lua"          = "~/.config/wezterm/wezterm.lua"
"files/config/wezterm/font.lua"             = "~/.config/wezterm/font.lua"
"files/config/wezterm/keybindings/init.lua" = "~/.config/wezterm/keybindings/init.lua"
"files/config/wezterm/keybindings/keys.lua" = "~/.config/wezterm/keybindings/keys.lua"
"files/config/wezterm/themes/init.lua"      = "~/.config/wezterm/themes/init.lua"
"files/config/wezterm/themes/no_image.lua"  = "~/.config/wezterm/themes/no_image.lua"
"files/config/wezterm/themes/use_image.lua" = "~/.config/wezterm/themes/use_image.lua"

[zellij.files]
"files/config/zellij/config.kdl"     = "~/.config/zellij/config.kdl"
"files/config/zellij/completion.zsh" = "~/.config/zellij/completion.zsh"

[zsh.files]
"files/zshrc"                       = "~/.zshrc"
"files/config/starship.toml"        = "~/.config/starship.toml"
"files/config/sheldon/plugins.toml" = "~/.config/sheldon/plugins.toml"
"files/config/zsh/alias.zsh"        = "~/.config/zsh/alias.zsh"
"files/config/zsh/completion.zsh"   = "~/.config/zsh/completion.zsh"
"files/config/zsh/hook.zsh"         = "~/.config/zsh/hook.zsh"
"files/config/zsh/option.zsh"       = "~/.config/zsh/option.zsh"
"files/config/zsh/ssh-agent.zsh"    = "~/.config/zsh/ssh-agent.zsh"
"files/config/zsh/style.zsh"        = "~/.config/zsh/style.zsh"

[settings]
default_target_type = "symbolic"
