[latex.files]
"files/override/windows/latexmkrc" = "~/.latexmkrc"
"files/override/windows/indentconfig.yaml" = "~/.indentconfig.yaml"
"files/override/windows/AppData/Local/latexindent/default.yaml" = "~/AppData/Local/latexindent/default.yaml"
"files/override/windows/AppData/Roaming/tex-fmt/tex-fmt.toml" = "~/AppData/Roaming/tex-fmt/tex-fmt.toml"

[nushell.files]
"files/override/windows/AppData/Roaming/nushell/config.nu" = "~/AppData/Roaming/nushell/config.nu"
"files/override/windows/AppData/Roaming/nushell/vendor/autoload/mise.nu" = "~/AppData/Roaming/nushell/vendor/autoload/mise.nu"
"files/override/windows/AppData/Roaming/nushell/vendor/autoload/ssh-agent.nu" = "~/AppData/Roaming/nushell/vendor/autoload/ssh-agent.nu"
"files/override/windows/AppData/Roaming/nushell/vendor/autoload/starship.nu" = "~/AppData/Roaming/nushell/vendor/autoload/starship.nu"
"files/override/windows/AppData/Roaming/nushell/vendor/autoload/yazi.nu" = "~/AppData/Roaming/nushell/vendor/autoload/yazi.nu"

[powershell.files]
"files/override/windows/Documents/PowerShell/Microsoft.PowerShell_profile.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"files/override/windows/AppData/Roaming/powershell/ssh-agent.ps1" = "~/AppData/Roaming/powershell/ssh-agent.ps1"

[vcxsrv.files]
"files/override/windows/config.xlaunch" = "~/.config.xlaunch"

[wsl.files]
"files/override/windows/wslconfig" = "~/.wslconfig"

# override
[lazygit]
depends = ["lazygit"]

[lazygit.files]
"files/config/lazygit/config.yml" = "~/AppData/Local/lazygit/config.yml"

# override
[neovide]
depends = ["neovide"]

[neovide.files]
"files/config/neovide/config.toml" = "~/AppData/Roaming/neovide/config.toml"

# override
[neovim]
depends = ["neovim"]

[neovim.files]
"files/config/nvim/init.lua" = "~/AppData/Local/nvim/init.lua"

"files/config/nvim/lua/base.lua" = "~/AppData/Local/nvim/lua/base.lua"
"files/config/nvim/lua/keymaps.lua" = "~/AppData/Local/nvim/lua/keymaps.lua"
"files/config/nvim/lua/lazy-nvim.lua" = "~/AppData/Local/nvim/lua/lazy-nvim.lua"
"files/config/nvim/lua/lsp.lua" = "~/AppData/Local/nvim/lua/lsp.lua"
"files/config/nvim/lua/neovide.lua" = "~/AppData/Local/nvim/lua/neovide.lua"

"files/config/nvim/lua/plugins/blink-cmp.lua" = "~/AppData/Local/nvim/lua/plugins/blink-cmp.lua"
"files/config/nvim/lua/plugins/gitsigns.lua" = "~/AppData/Local/nvim/lua/plugins/gitsigns.lua"
"files/config/nvim/lua/plugins/mason-lspconfig.lua" = "~/AppData/Local/nvim/lua/plugins/lsp/init.lua"
"files/config/nvim/lua/plugins/oil.lua" = "~/AppData/Local/nvim/lua/plugins/oil.lua"
"files/config/nvim/lua/plugins/remote-nvim.lua" = "~/AppData/Local/nvim/lua/plugins/remote-nvim.lua"
"files/config/nvim/lua/plugins/sidekick.lua" = "~/AppData/Local/nvim/lua/plugins/sidekick.lua"
"files/config/nvim/lua/plugins/snacks.lua" = "~/AppData/Local/nvim/lua/plugins/snacks.lua"
"files/config/nvim/lua/plugins/treesitter.lua" = "~/AppData/Local/nvim/lua/plugins/treesitter.lua"
"files/config/nvim/lua/plugins/treesitter-context.lua" = "~/AppData/Local/nvim/lua/plugins/treesitter-context.lua"
"files/config/nvim/lua/plugins/treesitter-textobjects.lua" = "~/AppData/Local/nvim/lua/plugins/treesitter-textobjects.lua"

"files/config/nvim/lua/plugins/snacks/dashboard.lua" = "~/AppData/Local/nvim/lua/plugins/snacks/dashboard.lua"
"files/config/nvim/lua/plugins/snacks/picker.lua" = "~/AppData/Local/nvim/lua/plugins/snacks/picker.lua"
"files/config/nvim/lua/plugins/snacks/notifier.lua" = "~/AppData/Local/nvim/lua/plugins/snacks/notifier.lua"

"files/config/nvim/lua/plugins/ui/colorscheme.lua" = "~/AppData/Local/nvim/lua/plugins/ui/colorscheme.lua"
"files/config/nvim/lua/plugins/ui/edgy.lua" = "~/AppData/Local/nvim/lua/plugins/ui/edgy.lua"
"files/config/nvim/lua/plugins/ui/lualine.lua" = "~/AppData/Local/nvim/lua/plugins/ui/lualine.lua"
"files/config/nvim/lua/plugins/ui/mini-icons.lua" = "~/AppData/Local/nvim/lua/plugins/ui/mini-icons.lua"
"files/config/nvim/lua/plugins/ui/render-markdown.lua" = "~/AppData/Local/nvim/lua/plugins/ui/render-markdown.lua"
"files/config/nvim/lua/plugins/ui/scrollbar.lua" = "~/AppData/Local/nvim/lua/plugins/ui/scrollbar.lua"
"files/config/nvim/lua/plugins/ui/smear-cursor.lua" = "~/AppData/Local/nvim/lua/plugins/ui/smear-cursor.lua"
"files/config/nvim/lua/plugins/ui/themes/kanagawa.lua" = "~/AppData/Local/nvim/lua/plugins/ui/themes/kanagawa.lua"

"files/config/nvim/lua/plugins/util/autopairs.lua" = "~/AppData/Local/nvim/lua/plugins/util/autopairs.lua"
"files/config/nvim/lua/plugins/util/buffer-sticks.lua" = "~/AppData/Local/nvim/lua/plugins/util/buffer-sticks.lua"
"files/config/nvim/lua/plugins/util/colorizer.lua" = "~/AppData/Local/nvim/lua/plugins/util/colorizer.lua"
"files/config/nvim/lua/plugins/util/conform.lua" = "~/AppData/Local/nvim/lua/plugins/util/conform.lua"
"files/config/nvim/lua/plugins/util/flash.lua" = "~/AppData/Local/nvim/lua/plugins/util/flash.lua"
"files/config/nvim/lua/plugins/util/hlslens.lua" = "~/AppData/Local/nvim/lua/plugins/util/hlslens.lua"
"files/config/nvim/lua/plugins/util/inc-rename.lua" = "~/AppData/Local/nvim/lua/plugins/util/inc-rename.lua"
"files/config/nvim/lua/plugins/util/origami.lua" = "~/AppData/Local/nvim/lua/plugins/util/origami.lua"
"files/config/nvim/lua/plugins/util/smart-splits.lua" = "~/AppData/Local/nvim/lua/plugins/util/smart-splits.lua"
"files/config/nvim/lua/plugins/util/startuptime.lua" = "~/AppData/Local/nvim/lua/plugins/util/startuptime.lua"
"files/config/nvim/lua/plugins/util/which-key.lua" = "~/AppData/Local/nvim/lua/plugins/util/which-key.lua"

"files/config/nvim/after/lsp/copilot.lua" = "~/AppData/Local/nvim/after/lsp/copilot.lua"
"files/config/nvim/after/lsp/lua_ls.lua" = "~/AppData/Local/nvim/after/lsp/lua_ls.lua"
