[wsl.files]
"files/override/windows/wslconfig" = "~/.wslconfig"

[vcxsrv.files]
"files/override/windows/config.xlaunch" = "~/.config.xlaunch"

[latex.files]
"files/override/windows/latexmkrc"                      = "~/.latexmkrc"
"files/override/windows/indentconfig.yaml"              = "~/.indentconfig.yaml"
"files/override/windows/latexindentconfig/default.yaml" = "~/.latexindentconfig/default.yaml"
"files/override/windows/config/tex-fmt/tex-fmt.toml"    = "~/AppData/Roaming/tex-fmt/tex-fmt.toml"

# override
[lazygit]
depends = ["lazygit"]

[lazygit.files]
"files/config/lazygit/config.yml" = "~/AppData/Local/lazygit/config.yml"

[nushell.files]
"files/override/windows/config/nushell/config.nu"                   = "~/AppData/Roaming/nushell/config.nu"
"files/override/windows/config/nushell/vendor/autoload/mise.nu"     = "~/AppData/Roaming/nushell/vendor/autoload/mise.nu"
"files/override/windows/config/nushell/vendor/autoload/starship.nu" = "~/AppData/Roaming/nushell/vendor/autoload/starship.nu"
"files/override/windows/config/nushell/vendor/autoload/yazi.nu"     = "~/AppData/Roaming/nushell/vendor/autoload/yazi.nu"

# override
[neovim]
depends = ["neovim"]

[neovim.files]
"files/config/nvim/init.lua"                                    = "~/AppData/Local/nvim/init.lua"

"files/config/nvim/lua/base.lua"                                = "~/AppData/Local/nvim/lua/base.lua"
"files/config/nvim/lua/keymaps.lua"                             = "~/AppData/Local/nvim/lua/keymaps.lua"
"files/config/nvim/lua/lazy-nvim.lua"                           = "~/AppData/Local/nvim/lua/lazy-nvim.lua"

"files/config/nvim/lua/plugins/blink-cmp.lua"                   = "~/AppData/Local/nvim/lua/plugins/blink-cmp.lua"
"files/config/nvim/lua/plugins/copilot.lua"                     = "~/AppData/Local/nvim/lua/plugins/copilot.lua"
"files/config/nvim/lua/plugins/lazygit.lua"                     = "~/AppData/Local/nvim/lua/plugins/lazygit.lua"
"files/config/nvim/lua/plugins/neo-tree.lua"                    = "~/AppData/Local/nvim/lua/plugins/neo-tree.lua"
"files/config/nvim/lua/plugins/remote-nvim.lua"                 = "~/AppData/Local/nvim/lua/plugins/remote-nvim.lua"
"files/config/nvim/lua/plugins/telescope.lua"                   = "~/AppData/Local/nvim/lua/plugins/telescope.lua"
"files/config/nvim/lua/plugins/treesitter.lua"                  = "~/AppData/Local/nvim/lua/plugins/treesitter.lua"
"files/config/nvim/lua/plugins/yazi.lua"                        = "~/AppData/Local/nvim/lua/plugins/yazi.lua"

"files/config/nvim/lua/plugins/lsp/init.lua"                    = "~/AppData/Local/nvim/lua/plugins/lsp/init.lua"
"files/config/nvim/lua/plugins/lsp/lua_ls.lua"                  = "~/AppData/Local/nvim/lua/plugins/lsp/lua_ls.lua"

"files/config/nvim/lua/plugins/ui/alpha.lua"                    = "~/AppData/Local/nvim/lua/plugins/ui/alpha.lua"
"files/config/nvim/lua/plugins/ui/bufresize.lua"                = "~/AppData/Local/nvim/lua/plugins/ui/bufresize.lua"
"files/config/nvim/lua/plugins/ui/kanagawa.lua"                 = "~/AppData/Local/nvim/lua/plugins/ui/kanagawa.lua"
"files/config/nvim/lua/plugins/ui/lsp-colors.lua"               = "~/AppData/Local/nvim/lua/plugins/ui/lsp-colors.lua"
"files/config/nvim/lua/plugins/ui/lualine.lua"                  = "~/AppData/Local/nvim/lua/plugins/ui/lualine.lua"
"files/config/nvim/lua/plugins/ui/modes.lua"                    = "~/AppData/Local/nvim/lua/plugins/ui/modes.lua"
"files/config/nvim/lua/plugins/ui/neoscroll.lua"                = "~/AppData/Local/nvim/lua/plugins/ui/neoscroll.lua"
"files/config/nvim/lua/plugins/ui/noice.lua"                    = "~/AppData/Local/nvim/lua/plugins/ui/noice.lua"
"files/config/nvim/lua/plugins/ui/notify.lua"                   = "~/AppData/Local/nvim/lua/plugins/ui/notify.lua"
"files/config/nvim/lua/plugins/ui/scrollbar.lua"                = "~/AppData/Local/nvim/lua/plugins/ui/scrollbar.lua"
"files/config/nvim/lua/plugins/ui/smear-cursor.lua"             = "~/AppData/Local/nvim/lua/plugins/ui/smear-cursor.lua"

"files/config/nvim/lua/plugins/util/autopairs.lua"              = "~/AppData/Local/nvim/lua/plugins/util/autopairs.lua"
"files/config/nvim/lua/plugins/util/bufferline.lua"             = "~/AppData/Local/nvim/lua/plugins/util/bufferline.lua"
"files/config/nvim/lua/plugins/util/comment.lua"                = "~/AppData/Local/nvim/lua/plugins/util/comment.lua"
"files/config/nvim/lua/plugins/util/markview.lua"               = "~/AppData/Local/nvim/lua/plugins/util/markview.lua"
"files/config/nvim/lua/plugins/util/startuptime.lua"            = "~/AppData/Local/nvim/lua/plugins/util/startuptime.lua"
"files/config/nvim/lua/plugins/util/which_key.lua"              = "~/AppData/Local/nvim/lua/plugins/util/which_key.lua"

"files/override/windows/config/nvim/lua/plugins/toggleterm.lua" = "~/AppData/Local/nvim/lua/plugins/toggleterm.lua"

# override
[wezterm]
depends = ["wezterm"]

[wezterm.files]
"files/override/windows/config/wezterm/wezterm.lua" = "~/.config/wezterm/wezterm.lua"
