name:
  .trash: ï‡¸
  .cargo: î¨
  .emacs.d: î¹
  a.out: ï’‰
extension:
  go: î˜§
  hs: î·
  rs: ğŸ¦€
filetype:
  dir: ï„•
  file: ğŸ“„
  pipe: ğŸ“©
  socket: ğŸ§¦
  executable: ï’‰
  symlink-dir: ï’‚
  symlink-file: ï’
  device-char: î˜
  device-block: î˜‚
  special: ï‹œ